#!/usr/bin/env ruby
site 'http://community.opscode.com/api/v1'

cookbook 'golang',
  :git => 'git@github.com:SimpleFinance/chef-golang.git'
cookbook 'java'
cookbook 'maven'
cookbook 'python'
cookbook 'rbenv',
  :git => 'git@github.com:fnichol/chef-rbenv.git'
cookbook 'ruby'
cookbook 'ruby_build'
cookbook 'polyglot',
  :path => './'
cookbook 'nodejs',
  :git => 'https://github.com/mdxp/nodejs-cookbook'
