name              'polyglot'
maintainer        'Simple Finance'
maintainer_email  'ops@simple.com'
license           'Apache 2.0'
description       'Easy defaults for ruby, python, clojure, java, and android'
version           '1.2.0'

depends 'golang'
depends 'java'
depends 'maven'
depends 'python'
depends 'rbenv'
depends 'ruby'
depends 'ruby_build'

